loki:
  auth_enabled: false
  storage:
    type: filesystem
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    filesystem:
      directory: /var/loki
      
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  extraEnv:
    - name: GOMEMLIMIT
      value: 450Mi
  extraVolumeMounts:
    - name: loki-storage
      mountPath: /var/loki
  extraVolumes:
    - name: loki-storage
      emptyDir: {}

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

gateway:
  enabled: false

resultsCache:
  enabled: false

minio:
  enabled: false

chunksCache:
  enabled: false


# loki:
#   auth_enabled: false
#   commonConfig:
#     replication_factor: 1
#   schemaConfig:
#     configs:
#       - from: 2024-04-01
#         store: tsdb
#         object_store: filesystem
#         schema: v13
#         index:
#           prefix: loki_index_
#           period: 24h

#   ingester:
#     chunk_encoding: snappy

#   tracing:
#     enabled: true

#   querier:
#     max_concurrent: 2

#   storage:
#     bucketNames:
#       chunks: loki-chunks
#       ruler: loki-ruler
#       admin: loki-admin
#     type: filesystem
#     filesystem:
#       directory: /var/loki

#   # storage_config:
#   #   type: filesystem
#   #   bucketNames:
#   #     chunks: loki-chunks
#   #     ruler: loki-ruler
#   #     admin: loki-admin
#   #   filesystem:
#   #     directory: /var/loki

# # canary:
# #   enabled: true
# #   lokiAddress: http://loki.monitoring.svc.cluster.local:3100

# gateway:
#   enabled: false

# resultsCache:
#   enabled: false

# deploymentMode: SingleBinary

# singleBinary:
#   replicas: 1
#   resources:
#     limits:
#       cpu: 500m
#       memory: 512Mi
#     requests:
#       cpu: 100m
#       memory: 128Mi
#   extraEnv:
#     - name: GOMEMLIMIT
#       value: 450Mi
#   extraVolumeMounts:
#     - name: loki-storage
#       mountPath: /var/loki
#   extraVolumes:
#     - name: loki-storage
#       emptyDir: {}

# chunksCache:
#   enabled: false
#   writebackSizeLimit: 10MB

# minio:
#   enabled: false

# backend:
#   replicas: 0
# read:
#   replicas: 0
# write:
#   replicas: 0
# ingester:
#   replicas: 0
# querier:
#   replicas: 0
# queryFrontend:
#   replicas: 0
# queryScheduler:
#   replicas: 0
# distributor:
#   replicas: 0
# compactor:
#   replicas: 0
# indexGateway:
#   replicas: 0
# bloomCompactor:
#   replicas: 0
# bloomGateway:
#   replicas: 0
